
version: "3"

services:
  db:
    build: "./sqlserver"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=armbook"
    volumes:
      - "mariadb_armbook:/armbook"
  webserver:
    build: "./webserver"
    ports:
      - "443:443"
    depends_on:
      - db
    links:
      - db
volumes:
  mariadb_armbook:
    driver: local